name: CI Test & Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy config examples
        run: |
          cp config/dev.exs.example config/dev.exs
          cp config/test.exs.example config/test.exs

      - name: Set up Erlang & Elixir via asdf
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.4"
          otp-version:   "28.0.1"

      - name: Cache dependencies & build artifacts
        uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-stock_stream-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-stock_stream-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile (warnings as errors)
        run: mix compile --warnings-as-errors

      - name: Setup database
        run: mix ecto.setup --quiet

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run tests
        run: MIX_ENV=test mix test --warnings-as-errors

      - name: Cache Dialyzer PLT
        uses: actions/cache@v3
        id: plt-cache
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-plt-

      - name: Build PLTs if cache miss
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer --halt-exit-status
